// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[name].tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/api/_imagick.ts";
import * as $3 from "./routes/api/image.ts";
import * as $4 from "./routes/api/podcast.ts";
import * as $5 from "./routes/content/[podcastName]/[episode].tsx";
import * as $6 from "./routes/content/[podcastName]/index.tsx";
import * as $7 from "./routes/feelingLucky.tsx";
import * as $8 from "./routes/form.tsx";
import * as $9 from "./routes/index.tsx";
import * as $$0 from "./islands/Counter.tsx";
import * as $$1 from "./islands/Image.tsx";
import * as $$2 from "./islands/Menu.tsx";
import * as $$3 from "./islands/Player.tsx";

const manifest = {
  routes: {
    "./routes/[name].tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/api/_imagick.ts": $2,
    "./routes/api/image.ts": $3,
    "./routes/api/podcast.ts": $4,
    "./routes/content/[podcastName]/[episode].tsx": $5,
    "./routes/content/[podcastName]/index.tsx": $6,
    "./routes/feelingLucky.tsx": $7,
    "./routes/form.tsx": $8,
    "./routes/index.tsx": $9,
  },
  islands: {
    "./islands/Counter.tsx": $$0,
    "./islands/Image.tsx": $$1,
    "./islands/Menu.tsx": $$2,
    "./islands/Player.tsx": $$3,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
